<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EcOrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ec_orders')->delete();
        
        \DB::table('ec_orders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 5,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '1606.00',
                'tax_amount' => '78.00',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '1528.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'VosKRo0iSQkYCZxulw9vNQyIhDJN5',
                'payment_id' => 1,
                'created_at' => '2022-03-15 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 7,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '735.70',
                'tax_amount' => '40.70',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '695.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'XK6PRxdhcNXccXKLXeFBAcSJDSWIs',
                'payment_id' => 2,
                'created_at' => '2022-03-06 08:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 2,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '483.90',
                'tax_amount' => '33.90',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '450.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'xzpOUYboI7XRWF4tvAv8VM8ZUI9tr',
                'payment_id' => 3,
                'created_at' => '2022-03-19 02:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 10,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '624.80',
                'tax_amount' => '23.80',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '601.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'PmOe1fCKRmjqgFWukVu7jVa2pgOZk',
                'payment_id' => 4,
                'created_at' => '2022-03-17 18:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'completed',
                'amount' => '1542.80',
                'tax_amount' => '82.80',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '1460.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => '6DRrC8IpyUMZJFvWb0nqGp4tDvpDK',
                'payment_id' => 5,
                'created_at' => '2022-03-07 06:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 11,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '956.90',
                'tax_amount' => '34.90',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '922.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'uT951I8ECbXePuV3r1oHXABPZwEC3',
                'payment_id' => 6,
                'created_at' => '2022-03-14 08:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 3,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'completed',
                'amount' => '660.00',
                'tax_amount' => '60.00',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '600.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'rSR82OlPu2brErYOsNIPOIql0Wz0X',
                'payment_id' => 7,
                'created_at' => '2022-03-11 06:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 2,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'completed',
                'amount' => '430.50',
                'tax_amount' => '20.50',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '410.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'l5IY8KUJ8IM1yOfgVHXAydIlGkTO0',
                'payment_id' => 8,
                'created_at' => '2022-03-14 02:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 2,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'completed',
                'amount' => '1330.00',
                'tax_amount' => '54.00',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '1276.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'PJNKsqF845uACrzUHfLQakiiLsn7B',
                'payment_id' => 9,
                'created_at' => '2022-03-17 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 4,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'completed',
                'amount' => '276.10',
                'tax_amount' => '14.10',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '262.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => '9CpW0RcUzpeE4uP89YpwxbuuuC1F5',
                'payment_id' => 10,
                'created_at' => '2022-03-12 08:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 3,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'completed',
                'amount' => '240.35',
                'tax_amount' => '21.85',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '218.50',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => '6K1HsGMx8fyrnVPAb6RYnvFbcyGGL',
                'payment_id' => 11,
                'created_at' => '2022-03-14 18:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 5,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '1965.50',
                'tax_amount' => '76.50',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '1889.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'MhPdT3ggPQOTk0acuActZQqdlI6tM',
                'payment_id' => 12,
                'created_at' => '2022-03-13 02:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 11,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'completed',
                'amount' => '1533.90',
                'tax_amount' => '60.90',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '1473.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'g7UCF2tBjEcMaZQ6xCnXX9usjs0o2',
                'payment_id' => 13,
                'created_at' => '2022-03-16 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 9,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'completed',
                'amount' => '304.50',
                'tax_amount' => '14.50',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '290.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'qneSli7OWXIK4AIuRtf9nH8gobJuv',
                'payment_id' => 14,
                'created_at' => '2022-03-15 22:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 6,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '608.55',
                'tax_amount' => '27.05',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '581.50',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'PKY96P7lIrkkEobjI8D1BRkm4cNV0',
                'payment_id' => 15,
                'created_at' => '2022-03-17 02:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 10,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '284.50',
                'tax_amount' => '14.50',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '270.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'jvCiC0rbDTetL7PcSPKyxbY8JGJcX',
                'payment_id' => 16,
                'created_at' => '2022-03-19 18:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 6,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '1069.80',
                'tax_amount' => '41.80',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '1028.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => '6NaoqrYjnArq8ZLhloIUM8NsGxZVf',
                'payment_id' => 17,
                'created_at' => '2022-03-18 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 6,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'completed',
                'amount' => '426.70',
                'tax_amount' => '22.70',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '404.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'w7vun6ejKV1mHpmMTlFCCDuB9qkCl',
                'payment_id' => 18,
                'created_at' => '2022-03-18 08:06:39',
                'updated_at' => '2022-03-20 14:06:39',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 3,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '518.83',
                'tax_amount' => '19.33',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '499.50',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => '8WkvLmIvy5L8ie2WhmQA5rJFslMBf',
                'payment_id' => 19,
                'created_at' => '2022-03-20 02:06:39',
                'updated_at' => '2022-03-20 14:06:39',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 11,
                'shipping_option' => '1',
                'shipping_method' => 'default',
                'status' => 'pending',
                'amount' => '745.90',
                'tax_amount' => '50.90',
                'shipping_amount' => '0.00',
                'description' => NULL,
                'coupon_code' => NULL,
                'discount_amount' => '0.00',
                'sub_total' => '695.00',
                'is_confirmed' => 1,
                'discount_description' => NULL,
                'is_finished' => 1,
                'token' => 'aOuCOI5LssPhqcVBqf6JdCb6jVBsY',
                'payment_id' => 20,
                'created_at' => '2022-03-20 10:06:39',
                'updated_at' => '2022-03-20 14:06:39',
            ),
        ));
        
        
    }
}