<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EcReviewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ec_reviews')->delete();
        
        \DB::table('ec_reviews')->insert(array (
            0 => 
            array (
                'id' => 1,
                'customer_id' => 1,
                'product_id' => 12,
                'star' => 2.0,
                'comment' => 'Best ecommerce CMS online store!',
                'status' => 'published',
                'created_at' => '2022-01-04 04:21:14',
                'updated_at' => '2022-01-04 04:21:14',
                'images' => '["products\\/2.jpg","products\\/6.jpg"]',
            ),
            1 => 
            array (
                'id' => 2,
                'customer_id' => 10,
                'product_id' => 1,
                'star' => 2.0,
                'comment' => 'Cool template. Excellent code quality. The support responds very quickly, which is very rare on themeforest and codecanyon.net, I buy a lot of templates, and everyone will have a response from technical support for two or three days. Thanks to tech support. I recommend to buy.',
                'status' => 'published',
                'created_at' => '2022-01-04 04:21:14',
                'updated_at' => '2022-01-04 04:21:14',
                'images' => '{"0":"products\\/1.jpg","2":"products\\/20.jpg"}',
            ),
            2 => 
            array (
                'id' => 3,
                'customer_id' => 7,
                'product_id' => 24,
                'star' => 4.0,
                'comment' => 'These guys are amazing! Responses immediately, amazing support and help... I immediately feel at ease after Purchasing..',
                'status' => 'published',
                'created_at' => '2022-01-04 04:21:14',
                'updated_at' => '2022-01-04 04:21:14',
                'images' => '["products\\/3.jpg","products\\/5.jpg"]',
            ),
            3 => 
            array (
                'id' => 4,
                'customer_id' => 11,
                'product_id' => 22,
                'star' => 2.0,
            'comment' => 'Customer Support are grade (A*), however the code is a way too over engineered for it\'s purpose.',
                'status' => 'published',
                'created_at' => '2022-01-04 04:21:14',
                'updated_at' => '2022-01-04 04:21:14',
                'images' => '["products\\/4.jpg","products\\/7.jpg"]',
            ),
            4 => 
            array (
                'id' => 5,
                'customer_id' => 3,
                'product_id' => 31,
                'star' => 1.0,
                'comment' => 'As a developer I reviewed this script. This is really awesome ecommerce script. I have convinced when I noticed that it\'s built on fully WordPress concept.',
                'status' => 'published',
                'created_at' => '2022-01-04 04:21:14',
                'updated_at' => '2022-01-04 04:21:14',
                'images' => '["products\\/2.jpg","products\\/6.jpg"]',
            ),
            5 => 
            array (
                'id' => 6,
                'customer_id' => 1,
                'product_id' => 19,
                'star' => 5.0,
                'comment' => 'Good app, good backup service and support. Good documentation.',
                'status' => 'published',
                'created_at' => '2022-01-04 04:21:14',
                'updated_at' => '2022-01-04 04:21:14',
                'images' => '["products\\/3.jpg"]',
            ),
            6 => 
            array (
                'id' => 7,
                'customer_id' => 6,
                'product_id' => 25,
                'star' => 4.0,
            'comment' => 'Those guys now what they are doing, the release such a good product that it\'s a pleasure to work with ! Even when I was stuck on the project, I created a ticket and the next day it was replied by the team. GOOD JOB guys. I love working with them :)',
            'status' => 'published',
            'created_at' => '2022-01-04 04:21:14',
            'updated_at' => '2022-01-04 04:21:14',
            'images' => '["products\\/1.jpg"]',
        ),
        7 => 
        array (
            'id' => 8,
            'customer_id' => 1,
            'product_id' => 5,
            'star' => 3.0,
            'comment' => 'This web app is really good in design, code quality & features. Besides, the customer support provided by the Botble team was really fast & helpful. You guys are awesome!',
            'status' => 'published',
            'created_at' => '2022-01-04 04:21:14',
            'updated_at' => '2022-01-04 04:21:14',
            'images' => '["products\\/4.jpg","products\\/5.jpg"]',
        ),
        8 => 
        array (
            'id' => 9,
            'customer_id' => 7,
            'product_id' => 4,
            'star' => 1.0,
            'comment' => 'Very enthusiastic support! Excellent code is written. It\'s a true pleasure working with.',
            'status' => 'published',
            'created_at' => '2022-01-04 04:21:14',
            'updated_at' => '2022-01-04 04:21:14',
            'images' => '["products\\/4.jpg","products\\/6.jpg"]',
        ),
        9 => 
        array (
            'id' => 10,
            'customer_id' => 1,
            'product_id' => 12,
            'star' => 3.0,
            'comment' => 'These guys are amazing! Responses immediately, amazing support and help... I immediately feel at ease after Purchasing..',
            'status' => 'published',
            'created_at' => '2022-01-04 04:21:14',
            'updated_at' => '2022-01-04 04:21:14',
            'images' => '["products\\/2.jpg","products\\/5.jpg"]',
        ),
        10 => 
        array (
            'id' => 11,
            'customer_id' => 8,
            'product_id' => 31,
            'star' => 3.0,
        'comment' => 'Second or third time that I buy a Botble product, happy with the products and support. You guys do a good job :)',
        'status' => 'published',
        'created_at' => '2022-01-04 04:21:14',
        'updated_at' => '2022-01-04 04:21:14',
        'images' => '["products\\/1.jpg","products\\/5.jpg"]',
    ),
    11 => 
    array (
        'id' => 12,
        'customer_id' => 8,
        'product_id' => 6,
        'star' => 3.0,
    'comment' => 'It\'s not my first experience here on Codecanyon and I can honestly tell you all that Botble puts a LOT of effort into the support. They answer so fast, they helped me tons of times. REALLY by far THE BEST EXPERIENCE on Codecanyon. Those guys at Botble are so good that they deserve 5 stars. I recommend them, I trust them and I can\'t wait to see what they will sell in a near future. Thank you Botble :)',
    'status' => 'published',
    'created_at' => '2022-01-04 04:21:14',
    'updated_at' => '2022-01-04 04:21:14',
    'images' => '["products\\/1.jpg","products\\/5.jpg","products\\/20.jpg"]',
),
12 => 
array (
    'id' => 13,
    'customer_id' => 6,
    'product_id' => 18,
    'star' => 1.0,
    'comment' => 'For me the best eCommerce script on Envato at this moment: modern, clean code, a lot of great features. The customer support is great too: I always get an answer within hours!',
    'status' => 'published',
    'created_at' => '2022-01-04 04:21:14',
    'updated_at' => '2022-01-04 04:21:14',
    'images' => '["products\\/4.jpg","products\\/7.jpg"]',
),
13 => 
array (
    'id' => 14,
    'customer_id' => 2,
    'product_id' => 2,
    'star' => 2.0,
    'comment' => 'As a developer I reviewed this script. This is really awesome ecommerce script. I have convinced when I noticed that it\'s built on fully WordPress concept.',
    'status' => 'published',
    'created_at' => '2022-01-04 04:21:14',
    'updated_at' => '2022-01-04 04:21:14',
    'images' => '["products\\/1.jpg","products\\/7.jpg"]',
),
14 => 
array (
    'id' => 15,
    'customer_id' => 9,
    'product_id' => 13,
    'star' => 5.0,
    'comment' => 'These guys are amazing! Responses immediately, amazing support and help... I immediately feel at ease after Purchasing..',
    'status' => 'published',
    'created_at' => '2022-01-04 04:21:14',
    'updated_at' => '2022-01-04 04:21:14',
    'images' => '["products\\/4.jpg","products\\/7.jpg","products\\/11.jpg"]',
),
15 => 
array (
    'id' => 16,
    'customer_id' => 6,
    'product_id' => 19,
    'star' => 2.0,
    'comment' => 'The best ecommerce CMS! Excellent coding! best support service! Thank you so much..... I really like your hard work.',
    'status' => 'published',
    'created_at' => '2022-01-04 04:21:14',
    'updated_at' => '2022-01-04 04:21:14',
    'images' => '["products\\/4.jpg","products\\/7.jpg","products\\/18.jpg"]',
),
16 => 
array (
    'id' => 17,
    'customer_id' => 3,
    'product_id' => 5,
    'star' => 1.0,
    'comment' => 'Perfect +++++++++ i love it really also i get to fast ticket answers... Thanks Lot BOTBLE Teams',
    'status' => 'published',
    'created_at' => '2022-01-04 04:21:14',
    'updated_at' => '2022-01-04 04:21:14',
    'images' => '["products\\/3.jpg"]',
),
17 => 
array (
    'id' => 18,
    'customer_id' => 4,
    'product_id' => 31,
    'star' => 2.0,
    'comment' => 'As a developer I reviewed this script. This is really awesome ecommerce script. I have convinced when I noticed that it\'s built on fully WordPress concept.',
    'status' => 'published',
    'created_at' => '2022-01-04 04:21:14',
    'updated_at' => '2022-01-04 04:21:14',
    'images' => '["products\\/4.jpg","products\\/5.jpg"]',
),
18 => 
array (
    'id' => 19,
    'customer_id' => 11,
    'product_id' => 3,
    'star' => 3.0,
'comment' => 'Those guys now what they are doing, the release such a good product that it\'s a pleasure to work with ! Even when I was stuck on the project, I created a ticket and the next day it was replied by the team. GOOD JOB guys. I love working with them :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/7.jpg"]',
),
19 => 
array (
'id' => 20,
'customer_id' => 3,
'product_id' => 22,
'star' => 2.0,
'comment' => 'Best ecommerce CMS online store!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/7.jpg"]',
),
20 => 
array (
'id' => 21,
'customer_id' => 9,
'product_id' => 28,
'star' => 4.0,
'comment' => 'Ok good product. I have some issues in customizations. But its not correct to blame the developer. The product is good. Good luck for your business.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg","products\\/29.jpg"]',
),
21 => 
array (
'id' => 22,
'customer_id' => 3,
'product_id' => 4,
'star' => 1.0,
'comment' => 'Good app, good backup service and support. Good documentation.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '{"0":"products\\/1.jpg","2":"products\\/9.jpg"}',
),
22 => 
array (
'id' => 23,
'customer_id' => 2,
'product_id' => 2,
'star' => 5.0,
'comment' => 'Ok good product. I have some issues in customizations. But its not correct to blame the developer. The product is good. Good luck for your business.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg"]',
),
23 => 
array (
'id' => 24,
'customer_id' => 2,
'product_id' => 16,
'star' => 5.0,
'comment' => 'Solution is too robust for our purpose so we didn\'t use it at the end. But I appreciate customer support during initial configuration.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg"]',
),
24 => 
array (
'id' => 25,
'customer_id' => 9,
'product_id' => 18,
'star' => 5.0,
'comment' => 'These guys are amazing! Responses immediately, amazing support and help... I immediately feel at ease after Purchasing..',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg"]',
),
25 => 
array (
'id' => 26,
'customer_id' => 1,
'product_id' => 19,
'star' => 5.0,
'comment' => 'Good app, good backup service and support. Good documentation.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/6.jpg"]',
),
26 => 
array (
'id' => 27,
'customer_id' => 1,
'product_id' => 16,
'star' => 4.0,
'comment' => 'Great system, great support, good job Botble. I\'m looking forward to more great functional plugins.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/7.jpg","products\\/9.jpg"]',
),
27 => 
array (
'id' => 28,
'customer_id' => 7,
'product_id' => 29,
'star' => 2.0,
'comment' => 'Ok good product. I have some issues in customizations. But its not correct to blame the developer. The product is good. Good luck for your business.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/5.jpg","products\\/18.jpg"]',
),
28 => 
array (
'id' => 29,
'customer_id' => 4,
'product_id' => 13,
'star' => 4.0,
'comment' => 'Ok good product. I have some issues in customizations. But its not correct to blame the developer. The product is good. Good luck for your business.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg"]',
),
29 => 
array (
'id' => 30,
'customer_id' => 9,
'product_id' => 13,
'star' => 3.0,
'comment' => 'The best store template! Excellent coding! Very good support! Thank you so much for all the help, I really appreciated.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg","products\\/5.jpg"]',
),
30 => 
array (
'id' => 31,
'customer_id' => 5,
'product_id' => 21,
'star' => 3.0,
'comment' => 'For me the best eCommerce script on Envato at this moment: modern, clean code, a lot of great features. The customer support is great too: I always get an answer within hours!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg"]',
),
31 => 
array (
'id' => 32,
'customer_id' => 11,
'product_id' => 23,
'star' => 2.0,
'comment' => 'Best ecommerce CMS online store!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/7.jpg"]',
),
32 => 
array (
'id' => 33,
'customer_id' => 7,
'product_id' => 11,
'star' => 5.0,
'comment' => 'These guys are amazing! Responses immediately, amazing support and help... I immediately feel at ease after Purchasing..',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/5.jpg","products\\/29.jpg"]',
),
33 => 
array (
'id' => 34,
'customer_id' => 1,
'product_id' => 14,
'star' => 3.0,
'comment' => 'The best ecommerce CMS! Excellent coding! best support service! Thank you so much..... I really like your hard work.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/5.jpg"]',
),
34 => 
array (
'id' => 35,
'customer_id' => 9,
'product_id' => 23,
'star' => 1.0,
'comment' => 'Best ecommerce CMS online store!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/6.jpg"]',
),
35 => 
array (
'id' => 36,
'customer_id' => 10,
'product_id' => 18,
'star' => 2.0,
'comment' => 'Customer Support are grade (A*), however the code is a way too over engineered for it\'s purpose.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/5.jpg","products\\/25.jpg"]',
),
36 => 
array (
'id' => 37,
'customer_id' => 2,
'product_id' => 20,
'star' => 3.0,
'comment' => 'For me the best eCommerce script on Envato at this moment: modern, clean code, a lot of great features. The customer support is great too: I always get an answer within hours!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/5.jpg"]',
),
37 => 
array (
'id' => 38,
'customer_id' => 2,
'product_id' => 27,
'star' => 1.0,
'comment' => 'I Love this Script. I also found how to add other fees. Now I just wait the BIG update for the Marketplace with the Bulk Import. Just do not forget to make it to be Multi-language for us the Botble Fans.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/6.jpg"]',
),
38 => 
array (
'id' => 39,
'customer_id' => 1,
'product_id' => 3,
'star' => 4.0,
'comment' => 'Amazing code, amazing support. Overall, im really confident in Botble and im happy I made the right choice! Thank you so much guys for coding this masterpiece',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/7.jpg","products\\/14.jpg"]',
),
39 => 
array (
'id' => 40,
'customer_id' => 5,
'product_id' => 8,
'star' => 5.0,
'comment' => 'For me the best eCommerce script on Envato at this moment: modern, clean code, a lot of great features. The customer support is great too: I always get an answer within hours!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/6.jpg","products\\/9.jpg"]',
),
40 => 
array (
'id' => 41,
'customer_id' => 4,
'product_id' => 6,
'star' => 3.0,
'comment' => 'Very enthusiastic support! Excellent code is written. It\'s a true pleasure working with.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg"]',
),
41 => 
array (
'id' => 42,
'customer_id' => 9,
'product_id' => 11,
'star' => 1.0,
'comment' => 'Those guys now what they are doing, the release such a good product that it\'s a pleasure to work with ! Even when I was stuck on the project, I created a ticket and the next day it was replied by the team. GOOD JOB guys. I love working with them :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg","products\\/6.jpg","products\\/20.jpg"]',
),
42 => 
array (
'id' => 43,
'customer_id' => 4,
'product_id' => 30,
'star' => 4.0,
'comment' => 'Best ecommerce CMS online store!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '{"0":"products\\/4.jpg","2":"products\\/9.jpg"}',
),
43 => 
array (
'id' => 44,
'customer_id' => 6,
'product_id' => 1,
'star' => 3.0,
'comment' => 'Great E-commerce system. And much more : Wonderful Customer Support.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/6.jpg"]',
),
44 => 
array (
'id' => 45,
'customer_id' => 7,
'product_id' => 11,
'star' => 4.0,
'comment' => 'It\'s not my first experience here on Codecanyon and I can honestly tell you all that Botble puts a LOT of effort into the support. They answer so fast, they helped me tons of times. REALLY by far THE BEST EXPERIENCE on Codecanyon. Those guys at Botble are so good that they deserve 5 stars. I recommend them, I trust them and I can\'t wait to see what they will sell in a near future. Thank you Botble :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg"]',
),
45 => 
array (
'id' => 46,
'customer_id' => 4,
'product_id' => 13,
'star' => 4.0,
'comment' => 'I Love this Script. I also found how to add other fees. Now I just wait the BIG update for the Marketplace with the Bulk Import. Just do not forget to make it to be Multi-language for us the Botble Fans.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg"]',
),
46 => 
array (
'id' => 47,
'customer_id' => 3,
'product_id' => 2,
'star' => 3.0,
'comment' => 'Great system, great support, good job Botble. I\'m looking forward to more great functional plugins.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg"]',
),
47 => 
array (
'id' => 48,
'customer_id' => 4,
'product_id' => 4,
'star' => 3.0,
'comment' => 'Ok good product. I have some issues in customizations. But its not correct to blame the developer. The product is good. Good luck for your business.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg","products\\/7.jpg"]',
),
48 => 
array (
'id' => 49,
'customer_id' => 3,
'product_id' => 8,
'star' => 2.0,
'comment' => 'Great E-commerce system. And much more : Wonderful Customer Support.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/6.jpg"]',
),
49 => 
array (
'id' => 50,
'customer_id' => 8,
'product_id' => 31,
'star' => 2.0,
'comment' => 'Clean & perfect source code',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/6.jpg"]',
),
50 => 
array (
'id' => 51,
'customer_id' => 7,
'product_id' => 26,
'star' => 5.0,
'comment' => 'Great E-commerce system. And much more : Wonderful Customer Support.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/5.jpg"]',
),
51 => 
array (
'id' => 52,
'customer_id' => 10,
'product_id' => 17,
'star' => 1.0,
'comment' => 'For me the best eCommerce script on Envato at this moment: modern, clean code, a lot of great features. The customer support is great too: I always get an answer within hours!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/7.jpg","products\\/19.jpg"]',
),
52 => 
array (
'id' => 53,
'customer_id' => 8,
'product_id' => 2,
'star' => 2.0,
'comment' => 'These guys are amazing! Responses immediately, amazing support and help... I immediately feel at ease after Purchasing..',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg"]',
),
53 => 
array (
'id' => 54,
'customer_id' => 1,
'product_id' => 1,
'star' => 5.0,
'comment' => 'Good app, good backup service and support. Good documentation.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg"]',
),
54 => 
array (
'id' => 55,
'customer_id' => 5,
'product_id' => 30,
'star' => 5.0,
'comment' => 'We have received brilliant service support and will be expanding the features with the developer. Nice product!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg","products\\/7.jpg"]',
),
55 => 
array (
'id' => 56,
'customer_id' => 6,
'product_id' => 28,
'star' => 3.0,
'comment' => 'Perfect +++++++++ i love it really also i get to fast ticket answers... Thanks Lot BOTBLE Teams',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/7.jpg","products\\/30.jpg"]',
),
56 => 
array (
'id' => 57,
'customer_id' => 6,
'product_id' => 27,
'star' => 3.0,
'comment' => 'Second or third time that I buy a Botble product, happy with the products and support. You guys do a good job :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg"]',
),
57 => 
array (
'id' => 58,
'customer_id' => 8,
'product_id' => 22,
'star' => 2.0,
'comment' => 'Great E-commerce system. And much more : Wonderful Customer Support.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/5.jpg"]',
),
58 => 
array (
'id' => 59,
'customer_id' => 10,
'product_id' => 22,
'star' => 1.0,
'comment' => 'This web app is really good in design, code quality & features. Besides, the customer support provided by the Botble team was really fast & helpful. You guys are awesome!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '{"0":"products\\/1.jpg","2":"products\\/24.jpg"}',
),
59 => 
array (
'id' => 60,
'customer_id' => 4,
'product_id' => 25,
'star' => 5.0,
'comment' => 'Clean & perfect source code',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/7.jpg","products\\/16.jpg"]',
),
60 => 
array (
'id' => 61,
'customer_id' => 9,
'product_id' => 27,
'star' => 1.0,
'comment' => 'For me the best eCommerce script on Envato at this moment: modern, clean code, a lot of great features. The customer support is great too: I always get an answer within hours!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg"]',
),
61 => 
array (
'id' => 62,
'customer_id' => 4,
'product_id' => 27,
'star' => 2.0,
'comment' => 'It\'s not my first experience here on Codecanyon and I can honestly tell you all that Botble puts a LOT of effort into the support. They answer so fast, they helped me tons of times. REALLY by far THE BEST EXPERIENCE on Codecanyon. Those guys at Botble are so good that they deserve 5 stars. I recommend them, I trust them and I can\'t wait to see what they will sell in a near future. Thank you Botble :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/7.jpg"]',
),
62 => 
array (
'id' => 63,
'customer_id' => 9,
'product_id' => 4,
'star' => 4.0,
'comment' => 'These guys are amazing! Responses immediately, amazing support and help... I immediately feel at ease after Purchasing..',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg"]',
),
63 => 
array (
'id' => 64,
'customer_id' => 4,
'product_id' => 19,
'star' => 2.0,
'comment' => 'I Love this Script. I also found how to add other fees. Now I just wait the BIG update for the Marketplace with the Bulk Import. Just do not forget to make it to be Multi-language for us the Botble Fans.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/7.jpg"]',
),
64 => 
array (
'id' => 65,
'customer_id' => 8,
'product_id' => 8,
'star' => 5.0,
'comment' => 'Great E-commerce system. And much more : Wonderful Customer Support.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg"]',
),
65 => 
array (
'id' => 66,
'customer_id' => 11,
'product_id' => 6,
'star' => 5.0,
'comment' => 'Solution is too robust for our purpose so we didn\'t use it at the end. But I appreciate customer support during initial configuration.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/6.jpg","products\\/13.jpg"]',
),
66 => 
array (
'id' => 67,
'customer_id' => 11,
'product_id' => 11,
'star' => 5.0,
'comment' => 'Ok good product. I have some issues in customizations. But its not correct to blame the developer. The product is good. Good luck for your business.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/6.jpg","products\\/12.jpg"]',
),
67 => 
array (
'id' => 68,
'customer_id' => 2,
'product_id' => 4,
'star' => 5.0,
'comment' => 'These guys are amazing! Responses immediately, amazing support and help... I immediately feel at ease after Purchasing..',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/5.jpg","products\\/31.jpg"]',
),
68 => 
array (
'id' => 69,
'customer_id' => 4,
'product_id' => 11,
'star' => 3.0,
'comment' => 'Cool template. Excellent code quality. The support responds very quickly, which is very rare on themeforest and codecanyon.net, I buy a lot of templates, and everyone will have a response from technical support for two or three days. Thanks to tech support. I recommend to buy.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg"]',
),
69 => 
array (
'id' => 70,
'customer_id' => 4,
'product_id' => 20,
'star' => 3.0,
'comment' => 'This script is well coded and is super fast. The support is pretty quick. Very patient and helpful team. I strongly recommend it and they deserve more than 5 stars.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg"]',
),
70 => 
array (
'id' => 71,
'customer_id' => 5,
'product_id' => 23,
'star' => 3.0,
'comment' => 'Second or third time that I buy a Botble product, happy with the products and support. You guys do a good job :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/5.jpg"]',
),
71 => 
array (
'id' => 72,
'customer_id' => 10,
'product_id' => 20,
'star' => 3.0,
'comment' => 'Those guys now what they are doing, the release such a good product that it\'s a pleasure to work with ! Even when I was stuck on the project, I created a ticket and the next day it was replied by the team. GOOD JOB guys. I love working with them :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg","products\\/5.jpg"]',
),
72 => 
array (
'id' => 73,
'customer_id' => 8,
'product_id' => 17,
'star' => 2.0,
'comment' => 'Those guys now what they are doing, the release such a good product that it\'s a pleasure to work with ! Even when I was stuck on the project, I created a ticket and the next day it was replied by the team. GOOD JOB guys. I love working with them :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/7.jpg"]',
),
73 => 
array (
'id' => 74,
'customer_id' => 11,
'product_id' => 6,
'star' => 2.0,
'comment' => 'Customer Support are grade (A*), however the code is a way too over engineered for it\'s purpose.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/5.jpg"]',
),
74 => 
array (
'id' => 75,
'customer_id' => 4,
'product_id' => 27,
'star' => 2.0,
'comment' => 'The code is good, in general, if you like it, can you give it 5 stars?',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/7.jpg"]',
),
75 => 
array (
'id' => 76,
'customer_id' => 2,
'product_id' => 6,
'star' => 1.0,
'comment' => 'The best ecommerce CMS! Excellent coding! best support service! Thank you so much..... I really like your hard work.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/5.jpg","products\\/19.jpg"]',
),
76 => 
array (
'id' => 77,
'customer_id' => 7,
'product_id' => 12,
'star' => 2.0,
'comment' => 'Second or third time that I buy a Botble product, happy with the products and support. You guys do a good job :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg","products\\/12.jpg"]',
),
77 => 
array (
'id' => 78,
'customer_id' => 1,
'product_id' => 19,
'star' => 1.0,
'comment' => 'Best ecommerce CMS online store!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/6.jpg"]',
),
78 => 
array (
'id' => 79,
'customer_id' => 11,
'product_id' => 22,
'star' => 4.0,
'comment' => 'Clean & perfect source code',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg","products\\/7.jpg"]',
),
79 => 
array (
'id' => 80,
'customer_id' => 5,
'product_id' => 16,
'star' => 2.0,
'comment' => 'Good app, good backup service and support. Good documentation.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg"]',
),
80 => 
array (
'id' => 81,
'customer_id' => 9,
'product_id' => 19,
'star' => 5.0,
'comment' => 'Second or third time that I buy a Botble product, happy with the products and support. You guys do a good job :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg"]',
),
81 => 
array (
'id' => 82,
'customer_id' => 9,
'product_id' => 17,
'star' => 1.0,
'comment' => 'The best store template! Excellent coding! Very good support! Thank you so much for all the help, I really appreciated.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg","products\\/6.jpg"]',
),
82 => 
array (
'id' => 83,
'customer_id' => 9,
'product_id' => 18,
'star' => 5.0,
'comment' => 'Those guys now what they are doing, the release such a good product that it\'s a pleasure to work with ! Even when I was stuck on the project, I created a ticket and the next day it was replied by the team. GOOD JOB guys. I love working with them :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/6.jpg","products\\/14.jpg"]',
),
83 => 
array (
'id' => 84,
'customer_id' => 10,
'product_id' => 13,
'star' => 1.0,
'comment' => 'These guys are amazing! Responses immediately, amazing support and help... I immediately feel at ease after Purchasing..',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg","products\\/7.jpg"]',
),
84 => 
array (
'id' => 85,
'customer_id' => 3,
'product_id' => 9,
'star' => 4.0,
'comment' => 'Second or third time that I buy a Botble product, happy with the products and support. You guys do a good job :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/7.jpg","products\\/21.jpg"]',
),
85 => 
array (
'id' => 86,
'customer_id' => 10,
'product_id' => 15,
'star' => 3.0,
'comment' => 'Perfect +++++++++ i love it really also i get to fast ticket answers... Thanks Lot BOTBLE Teams',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/7.jpg","products\\/12.jpg"]',
),
86 => 
array (
'id' => 87,
'customer_id' => 10,
'product_id' => 2,
'star' => 5.0,
'comment' => 'Great system, great support, good job Botble. I\'m looking forward to more great functional plugins.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/5.jpg"]',
),
87 => 
array (
'id' => 88,
'customer_id' => 7,
'product_id' => 31,
'star' => 1.0,
'comment' => 'Solution is too robust for our purpose so we didn\'t use it at the end. But I appreciate customer support during initial configuration.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/5.jpg","products\\/16.jpg"]',
),
88 => 
array (
'id' => 89,
'customer_id' => 8,
'product_id' => 21,
'star' => 1.0,
'comment' => 'It\'s not my first experience here on Codecanyon and I can honestly tell you all that Botble puts a LOT of effort into the support. They answer so fast, they helped me tons of times. REALLY by far THE BEST EXPERIENCE on Codecanyon. Those guys at Botble are so good that they deserve 5 stars. I recommend them, I trust them and I can\'t wait to see what they will sell in a near future. Thank you Botble :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg"]',
),
89 => 
array (
'id' => 90,
'customer_id' => 7,
'product_id' => 6,
'star' => 5.0,
'comment' => 'This web app is really good in design, code quality & features. Besides, the customer support provided by the Botble team was really fast & helpful. You guys are awesome!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/6.jpg","products\\/17.jpg"]',
),
90 => 
array (
'id' => 91,
'customer_id' => 3,
'product_id' => 29,
'star' => 3.0,
'comment' => 'The best ecommerce CMS! Excellent coding! best support service! Thank you so much..... I really like your hard work.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '{"0":"products\\/4.jpg","2":"products\\/17.jpg"}',
),
91 => 
array (
'id' => 92,
'customer_id' => 5,
'product_id' => 10,
'star' => 3.0,
'comment' => 'Great system, great support, good job Botble. I\'m looking forward to more great functional plugins.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg"]',
),
92 => 
array (
'id' => 93,
'customer_id' => 11,
'product_id' => 8,
'star' => 3.0,
'comment' => 'Good app, good backup service and support. Good documentation.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/2.jpg"]',
),
93 => 
array (
'id' => 94,
'customer_id' => 6,
'product_id' => 11,
'star' => 3.0,
'comment' => 'Great system, great support, good job Botble. I\'m looking forward to more great functional plugins.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/5.jpg"]',
),
94 => 
array (
'id' => 95,
'customer_id' => 7,
'product_id' => 10,
'star' => 5.0,
'comment' => 'The script is the best of its class, fast, easy to implement and work with , and the most important thing is the great support team , Recommend with no doubt.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '{"0":"products\\/3.jpg","2":"products\\/13.jpg"}',
),
95 => 
array (
'id' => 96,
'customer_id' => 1,
'product_id' => 2,
'star' => 2.0,
'comment' => 'Second or third time that I buy a Botble product, happy with the products and support. You guys do a good job :)',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/6.jpg"]',
),
96 => 
array (
'id' => 97,
'customer_id' => 1,
'product_id' => 9,
'star' => 3.0,
'comment' => 'For me the best eCommerce script on Envato at this moment: modern, clean code, a lot of great features. The customer support is great too: I always get an answer within hours!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/1.jpg","products\\/5.jpg","products\\/27.jpg"]',
),
97 => 
array (
'id' => 98,
'customer_id' => 2,
'product_id' => 28,
'star' => 2.0,
'comment' => 'Cool template. Excellent code quality. The support responds very quickly, which is very rare on themeforest and codecanyon.net, I buy a lot of templates, and everyone will have a response from technical support for two or three days. Thanks to tech support. I recommend to buy.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/3.jpg","products\\/6.jpg","products\\/30.jpg"]',
),
98 => 
array (
'id' => 99,
'customer_id' => 7,
'product_id' => 13,
'star' => 1.0,
'comment' => 'The best store template! Excellent coding! Very good support! Thank you so much for all the help, I really appreciated.',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '["products\\/4.jpg","products\\/6.jpg"]',
),
99 => 
array (
'id' => 100,
'customer_id' => 9,
'product_id' => 27,
'star' => 1.0,
'comment' => 'We have received brilliant service support and will be expanding the features with the developer. Nice product!',
'status' => 'published',
'created_at' => '2022-01-04 04:21:14',
'updated_at' => '2022-01-04 04:21:14',
'images' => '{"0":"products\\/1.jpg","2":"products\\/27.jpg"}',
),
));
        
        
    }
}