<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaFilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media_files')->delete();
        
        \DB::table('media_files')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 0,
                'name' => '1',
                'folder_id' => 1,
                'mime_type' => 'image/png',
                'size' => 3509,
                'url' => 'brands/1.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:42',
                'updated_at' => '2022-01-04 04:20:42',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 0,
                'name' => '2',
                'folder_id' => 1,
                'mime_type' => 'image/png',
                'size' => 3505,
                'url' => 'brands/2.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:43',
                'updated_at' => '2022-01-04 04:20:43',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 0,
                'name' => '3',
                'folder_id' => 1,
                'mime_type' => 'image/png',
                'size' => 2585,
                'url' => 'brands/3.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:43',
                'updated_at' => '2022-01-04 04:20:43',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 0,
                'name' => '4',
                'folder_id' => 1,
                'mime_type' => 'image/png',
                'size' => 6427,
                'url' => 'brands/4.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:43',
                'updated_at' => '2022-01-04 04:20:43',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 0,
                'name' => '5',
                'folder_id' => 1,
                'mime_type' => 'image/png',
                'size' => 3246,
                'url' => 'brands/5.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:43',
                'updated_at' => '2022-01-04 04:20:43',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 0,
                'name' => '6',
                'folder_id' => 1,
                'mime_type' => 'image/png',
                'size' => 3276,
                'url' => 'brands/6.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:43',
                'updated_at' => '2022-01-04 04:20:43',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 0,
                'name' => '7',
                'folder_id' => 1,
                'mime_type' => 'image/png',
                'size' => 3120,
                'url' => 'brands/7.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:43',
                'updated_at' => '2022-01-04 04:20:43',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 0,
                'name' => 'p-1',
                'folder_id' => 2,
                'mime_type' => 'image/png',
                'size' => 9577,
                'url' => 'product-categories/p-1.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:43',
                'updated_at' => '2022-01-04 04:20:43',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 0,
                'name' => 'p-2',
                'folder_id' => 2,
                'mime_type' => 'image/png',
                'size' => 5510,
                'url' => 'product-categories/p-2.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:44',
                'updated_at' => '2022-01-04 04:20:44',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 0,
                'name' => 'p-3',
                'folder_id' => 2,
                'mime_type' => 'image/png',
                'size' => 16215,
                'url' => 'product-categories/p-3.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:44',
                'updated_at' => '2022-01-04 04:20:44',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 0,
                'name' => 'p-4',
                'folder_id' => 2,
                'mime_type' => 'image/png',
                'size' => 7394,
                'url' => 'product-categories/p-4.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:44',
                'updated_at' => '2022-01-04 04:20:44',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 0,
                'name' => 'p-5',
                'folder_id' => 2,
                'mime_type' => 'image/png',
                'size' => 6714,
                'url' => 'product-categories/p-5.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:44',
                'updated_at' => '2022-01-04 04:20:44',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 0,
                'name' => 'p-6',
                'folder_id' => 2,
                'mime_type' => 'image/png',
                'size' => 9541,
                'url' => 'product-categories/p-6.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:44',
                'updated_at' => '2022-01-04 04:20:44',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 0,
                'name' => 'p-7',
                'folder_id' => 2,
                'mime_type' => 'image/png',
                'size' => 13677,
                'url' => 'product-categories/p-7.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:44',
                'updated_at' => '2022-01-04 04:20:44',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 0,
                'name' => '1',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 11752,
                'url' => 'customers/1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:45',
                'updated_at' => '2022-01-04 04:20:45',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 0,
                'name' => '10',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 27814,
                'url' => 'customers/10.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:45',
                'updated_at' => '2022-01-04 04:20:45',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 0,
                'name' => '2',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 19005,
                'url' => 'customers/2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:45',
                'updated_at' => '2022-01-04 04:20:45',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 0,
                'name' => '3',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 20400,
                'url' => 'customers/3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:45',
                'updated_at' => '2022-01-04 04:20:45',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 0,
                'name' => '4',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 26819,
                'url' => 'customers/4.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:46',
                'updated_at' => '2022-01-04 04:20:46',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 0,
                'name' => '5',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 14367,
                'url' => 'customers/5.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:46',
                'updated_at' => '2022-01-04 04:20:46',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 0,
                'name' => '6',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 12367,
                'url' => 'customers/6.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:46',
                'updated_at' => '2022-01-04 04:20:46',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 0,
                'name' => '7',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 20652,
                'url' => 'customers/7.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:46',
                'updated_at' => '2022-01-04 04:20:46',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 0,
                'name' => '8',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 21164,
                'url' => 'customers/8.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:46',
                'updated_at' => '2022-01-04 04:20:46',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 0,
                'name' => '9',
                'folder_id' => 3,
                'mime_type' => 'image/jpeg',
                'size' => 6084,
                'url' => 'customers/9.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:46',
                'updated_at' => '2022-01-04 04:20:46',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 0,
                'name' => '1-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 88437,
                'url' => 'products/1-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:47',
                'updated_at' => '2022-01-04 04:20:47',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 0,
                'name' => '1-2',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 122690,
                'url' => 'products/1-2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:48',
                'updated_at' => '2022-01-04 04:20:48',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 0,
                'name' => '1-3',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 117296,
                'url' => 'products/1-3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:48',
                'updated_at' => '2022-01-04 04:20:48',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 0,
                'name' => '1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 139025,
                'url' => 'products/1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:48',
                'updated_at' => '2022-01-04 04:20:48',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 0,
                'name' => '10-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 183491,
                'url' => 'products/10-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:49',
                'updated_at' => '2022-01-04 04:20:49',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 0,
                'name' => '10',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 150956,
                'url' => 'products/10.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:49',
                'updated_at' => '2022-01-04 04:20:49',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 0,
                'name' => '11-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 246200,
                'url' => 'products/11-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:49',
                'updated_at' => '2022-01-04 04:20:49',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 0,
                'name' => '11',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 279390,
                'url' => 'products/11.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:50',
                'updated_at' => '2022-01-04 04:20:50',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 0,
                'name' => '12-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 249712,
                'url' => 'products/12-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:50',
                'updated_at' => '2022-01-04 04:20:50',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 0,
                'name' => '12',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 172221,
                'url' => 'products/12.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:50',
                'updated_at' => '2022-01-04 04:20:50',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 0,
                'name' => '13-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 257021,
                'url' => 'products/13-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:51',
                'updated_at' => '2022-01-04 04:20:51',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 0,
                'name' => '13',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 232917,
                'url' => 'products/13.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:51',
                'updated_at' => '2022-01-04 04:20:51',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 0,
                'name' => '14-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 201773,
                'url' => 'products/14-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:51',
                'updated_at' => '2022-01-04 04:20:51',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 0,
                'name' => '14',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 287194,
                'url' => 'products/14.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:52',
                'updated_at' => '2022-01-04 04:20:52',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 0,
                'name' => '15-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 273720,
                'url' => 'products/15-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:52',
                'updated_at' => '2022-01-04 04:20:52',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 0,
                'name' => '15',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 114265,
                'url' => 'products/15.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:52',
                'updated_at' => '2022-01-04 04:20:52',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 0,
                'name' => '16',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 97174,
                'url' => 'products/16.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:52',
                'updated_at' => '2022-01-04 04:20:52',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 0,
                'name' => '17',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 70179,
                'url' => 'products/17.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:53',
                'updated_at' => '2022-01-04 04:20:53',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 0,
                'name' => '18-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 287835,
                'url' => 'products/18-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:54',
                'updated_at' => '2022-01-04 04:20:54',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 0,
                'name' => '18-2',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 454869,
                'url' => 'products/18-2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:55',
                'updated_at' => '2022-01-04 04:20:55',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 0,
                'name' => '18',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 257331,
                'url' => 'products/18.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:56',
                'updated_at' => '2022-01-04 04:20:56',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 0,
                'name' => '19-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 144008,
                'url' => 'products/19-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:56',
                'updated_at' => '2022-01-04 04:20:56',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 0,
                'name' => '19',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 188821,
                'url' => 'products/19.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:57',
                'updated_at' => '2022-01-04 04:20:57',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 0,
                'name' => '2-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 138167,
                'url' => 'products/2-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:57',
                'updated_at' => '2022-01-04 04:20:57',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 0,
                'name' => '2-2',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 230552,
                'url' => 'products/2-2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:57',
                'updated_at' => '2022-01-04 04:20:57',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 0,
                'name' => '2-3',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 179301,
                'url' => 'products/2-3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:58',
                'updated_at' => '2022-01-04 04:20:58',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 0,
                'name' => '2',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 130048,
                'url' => 'products/2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:58',
                'updated_at' => '2022-01-04 04:20:58',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 0,
                'name' => '20-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 249712,
                'url' => 'products/20-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:58',
                'updated_at' => '2022-01-04 04:20:58',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 0,
                'name' => '20',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 172221,
                'url' => 'products/20.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:58',
                'updated_at' => '2022-01-04 04:20:58',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 0,
                'name' => '21-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 260746,
                'url' => 'products/21-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:59',
                'updated_at' => '2022-01-04 04:20:59',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 0,
                'name' => '21',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 124244,
                'url' => 'products/21.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:20:59',
                'updated_at' => '2022-01-04 04:20:59',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 0,
                'name' => '22-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 268620,
                'url' => 'products/22-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:00',
                'updated_at' => '2022-01-04 04:21:00',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 0,
                'name' => '22',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 128692,
                'url' => 'products/22.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:01',
                'updated_at' => '2022-01-04 04:21:01',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 0,
                'name' => '23-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 105560,
                'url' => 'products/23-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:01',
                'updated_at' => '2022-01-04 04:21:01',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 0,
                'name' => '23',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 177362,
                'url' => 'products/23.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:02',
                'updated_at' => '2022-01-04 04:21:02',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 0,
                'name' => '24-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 239311,
                'url' => 'products/24-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:03',
                'updated_at' => '2022-01-04 04:21:03',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 0,
                'name' => '24',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 363853,
                'url' => 'products/24.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:03',
                'updated_at' => '2022-01-04 04:21:03',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 0,
                'name' => '25-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 17089,
                'url' => 'products/25-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:04',
                'updated_at' => '2022-01-04 04:21:04',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 0,
                'name' => '25',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 18069,
                'url' => 'products/25.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:05',
                'updated_at' => '2022-01-04 04:21:05',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 0,
                'name' => '26-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 13085,
                'url' => 'products/26-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:05',
                'updated_at' => '2022-01-04 04:21:05',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 0,
                'name' => '26-2',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 22667,
                'url' => 'products/26-2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:05',
                'updated_at' => '2022-01-04 04:21:05',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 0,
                'name' => '26',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 13611,
                'url' => 'products/26.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:05',
                'updated_at' => '2022-01-04 04:21:05',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'user_id' => 0,
                'name' => '27-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 10286,
                'url' => 'products/27-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:06',
                'updated_at' => '2022-01-04 04:21:06',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'user_id' => 0,
                'name' => '27',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 12569,
                'url' => 'products/27.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:06',
                'updated_at' => '2022-01-04 04:21:06',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'user_id' => 0,
                'name' => '28-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 15654,
                'url' => 'products/28-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:06',
                'updated_at' => '2022-01-04 04:21:06',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'user_id' => 0,
                'name' => '28',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 18243,
                'url' => 'products/28.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:06',
                'updated_at' => '2022-01-04 04:21:06',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'user_id' => 0,
                'name' => '29-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 27890,
                'url' => 'products/29-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:06',
                'updated_at' => '2022-01-04 04:21:06',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'user_id' => 0,
                'name' => '29',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 27961,
                'url' => 'products/29.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:06',
                'updated_at' => '2022-01-04 04:21:06',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'user_id' => 0,
                'name' => '3-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 135741,
                'url' => 'products/3-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:06',
                'updated_at' => '2022-01-04 04:21:06',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'user_id' => 0,
                'name' => '3-2',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 123069,
                'url' => 'products/3-2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:06',
                'updated_at' => '2022-01-04 04:21:06',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'user_id' => 0,
                'name' => '3-3',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 98645,
                'url' => 'products/3-3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:07',
                'updated_at' => '2022-01-04 04:21:07',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'user_id' => 0,
                'name' => '3',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 201722,
                'url' => 'products/3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:07',
                'updated_at' => '2022-01-04 04:21:07',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'user_id' => 0,
                'name' => '30-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 26283,
                'url' => 'products/30-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:07',
                'updated_at' => '2022-01-04 04:21:07',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'user_id' => 0,
                'name' => '30',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 27107,
                'url' => 'products/30.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:07',
                'updated_at' => '2022-01-04 04:21:07',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'user_id' => 0,
                'name' => '31-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 25924,
                'url' => 'products/31-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:08',
                'updated_at' => '2022-01-04 04:21:08',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'user_id' => 0,
                'name' => '31',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 18634,
                'url' => 'products/31.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:08',
                'updated_at' => '2022-01-04 04:21:08',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'user_id' => 0,
                'name' => '4-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 205312,
                'url' => 'products/4-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:08',
                'updated_at' => '2022-01-04 04:21:08',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'user_id' => 0,
                'name' => '4-2',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 223903,
                'url' => 'products/4-2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:08',
                'updated_at' => '2022-01-04 04:21:08',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'user_id' => 0,
                'name' => '4-3',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 106593,
                'url' => 'products/4-3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:08',
                'updated_at' => '2022-01-04 04:21:08',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'user_id' => 0,
                'name' => '4',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 456134,
                'url' => 'products/4.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:09',
                'updated_at' => '2022-01-04 04:21:09',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'user_id' => 0,
                'name' => '5-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 110014,
                'url' => 'products/5-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:09',
                'updated_at' => '2022-01-04 04:21:09',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'user_id' => 0,
                'name' => '5-2',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 104934,
                'url' => 'products/5-2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:09',
                'updated_at' => '2022-01-04 04:21:09',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'user_id' => 0,
                'name' => '5-3',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 131628,
                'url' => 'products/5-3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:09',
                'updated_at' => '2022-01-04 04:21:09',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'user_id' => 0,
                'name' => '5',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 214767,
                'url' => 'products/5.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:10',
                'updated_at' => '2022-01-04 04:21:10',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'user_id' => 0,
                'name' => '6-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 128041,
                'url' => 'products/6-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:10',
                'updated_at' => '2022-01-04 04:21:10',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'user_id' => 0,
                'name' => '6',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 148485,
                'url' => 'products/6.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:10',
                'updated_at' => '2022-01-04 04:21:10',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'user_id' => 0,
                'name' => '7-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 144008,
                'url' => 'products/7-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:11',
                'updated_at' => '2022-01-04 04:21:11',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'user_id' => 0,
                'name' => '7',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 188821,
                'url' => 'products/7.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:11',
                'updated_at' => '2022-01-04 04:21:11',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'user_id' => 0,
                'name' => '8-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 274272,
                'url' => 'products/8-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:11',
                'updated_at' => '2022-01-04 04:21:11',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'user_id' => 0,
                'name' => '8',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 217862,
                'url' => 'products/8.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:11',
                'updated_at' => '2022-01-04 04:21:11',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'user_id' => 0,
                'name' => '9-1',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 65624,
                'url' => 'products/9-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:12',
                'updated_at' => '2022-01-04 04:21:12',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'user_id' => 0,
                'name' => '9',
                'folder_id' => 4,
                'mime_type' => 'image/jpeg',
                'size' => 159636,
                'url' => 'products/9.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:12',
                'updated_at' => '2022-01-04 04:21:12',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'user_id' => 0,
                'name' => '1',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 82629,
                'url' => 'news/1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:15',
                'updated_at' => '2022-01-04 04:21:15',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'user_id' => 0,
                'name' => '10',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 342651,
                'url' => 'news/10.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:15',
                'updated_at' => '2022-01-04 04:21:15',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'user_id' => 0,
                'name' => '11',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 296740,
                'url' => 'news/11.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:15',
                'updated_at' => '2022-01-04 04:21:15',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'user_id' => 0,
                'name' => '2',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 119904,
                'url' => 'news/2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:16',
                'updated_at' => '2022-01-04 04:21:16',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'user_id' => 0,
                'name' => '3',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 89543,
                'url' => 'news/3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:16',
                'updated_at' => '2022-01-04 04:21:16',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'user_id' => 0,
                'name' => '4',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 51573,
                'url' => 'news/4.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:16',
                'updated_at' => '2022-01-04 04:21:16',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'user_id' => 0,
                'name' => '5',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 41164,
                'url' => 'news/5.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:16',
                'updated_at' => '2022-01-04 04:21:16',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'user_id' => 0,
                'name' => '6',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 80696,
                'url' => 'news/6.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:16',
                'updated_at' => '2022-01-04 04:21:16',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'user_id' => 0,
                'name' => '7',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 904027,
                'url' => 'news/7.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:16',
                'updated_at' => '2022-01-04 04:21:16',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'user_id' => 0,
                'name' => '8',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 351088,
                'url' => 'news/8.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:17',
                'updated_at' => '2022-01-04 04:21:17',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'user_id' => 0,
                'name' => '9',
                'folder_id' => 5,
                'mime_type' => 'image/jpeg',
                'size' => 353751,
                'url' => 'news/9.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:17',
                'updated_at' => '2022-01-04 04:21:17',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'user_id' => 0,
                'name' => '1',
                'folder_id' => 6,
                'mime_type' => 'image/jpeg',
                'size' => 2733,
                'url' => 'testimonials/1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:18',
                'updated_at' => '2022-01-04 04:21:18',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'user_id' => 0,
                'name' => '2',
                'folder_id' => 6,
                'mime_type' => 'image/jpeg',
                'size' => 2840,
                'url' => 'testimonials/2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:18',
                'updated_at' => '2022-01-04 04:21:18',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'user_id' => 0,
                'name' => '3',
                'folder_id' => 6,
                'mime_type' => 'image/jpeg',
                'size' => 3065,
                'url' => 'testimonials/3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:18',
                'updated_at' => '2022-01-04 04:21:18',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'user_id' => 0,
                'name' => '4',
                'folder_id' => 6,
                'mime_type' => 'image/jpeg',
                'size' => 2559,
                'url' => 'testimonials/4.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:18',
                'updated_at' => '2022-01-04 04:21:18',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'user_id' => 0,
                'name' => '1',
                'folder_id' => 7,
                'mime_type' => 'image/jpeg',
                'size' => 98636,
                'url' => 'sliders/1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:18',
                'updated_at' => '2022-01-04 04:21:18',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'user_id' => 0,
                'name' => '2',
                'folder_id' => 7,
                'mime_type' => 'image/jpeg',
                'size' => 22560,
                'url' => 'sliders/2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:19',
                'updated_at' => '2022-01-04 04:21:19',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'user_id' => 0,
                'name' => '3',
                'folder_id' => 7,
                'mime_type' => 'image/jpeg',
                'size' => 21630,
                'url' => 'sliders/3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:19',
                'updated_at' => '2022-01-04 04:21:19',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'user_id' => 0,
                'name' => 'american-express',
                'folder_id' => 8,
                'mime_type' => 'image/png',
                'size' => 3209,
                'url' => 'general/american-express.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'user_id' => 0,
                'name' => 'b-1',
                'folder_id' => 8,
                'mime_type' => 'image/jpeg',
                'size' => 20539,
                'url' => 'general/b-1.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'user_id' => 0,
                'name' => 'b-2',
                'folder_id' => 8,
                'mime_type' => 'image/jpeg',
                'size' => 18320,
                'url' => 'general/b-2.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'user_id' => 0,
                'name' => 'b-3',
                'folder_id' => 8,
                'mime_type' => 'image/jpeg',
                'size' => 42872,
                'url' => 'general/b-3.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'user_id' => 0,
                'name' => 'discover',
                'folder_id' => 8,
                'mime_type' => 'image/png',
                'size' => 2494,
                'url' => 'general/discover.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:21',
                'updated_at' => '2022-01-04 04:21:21',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'user_id' => 0,
                'name' => 'favicon',
                'folder_id' => 8,
                'mime_type' => 'image/png',
                'size' => 1803,
                'url' => 'general/favicon.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:21',
                'updated_at' => '2022-01-04 04:21:21',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'user_id' => 0,
                'name' => 'logo-light',
                'folder_id' => 8,
                'mime_type' => 'image/png',
                'size' => 3736,
                'url' => 'general/logo-light.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:21',
                'updated_at' => '2022-01-04 04:21:21',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'user_id' => 0,
                'name' => 'logo',
                'folder_id' => 8,
                'mime_type' => 'image/png',
                'size' => 3927,
                'url' => 'general/logo.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:21',
                'updated_at' => '2022-01-04 04:21:21',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'user_id' => 0,
                'name' => 'master-card',
                'folder_id' => 8,
                'mime_type' => 'image/png',
                'size' => 3407,
                'url' => 'general/master-card.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:21',
                'updated_at' => '2022-01-04 04:21:21',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'user_id' => 0,
                'name' => 'newsletter',
                'folder_id' => 8,
                'mime_type' => 'image/jpeg',
                'size' => 48929,
                'url' => 'general/newsletter.jpg',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:22',
                'updated_at' => '2022-01-04 04:21:22',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'user_id' => 0,
                'name' => 'paypal',
                'folder_id' => 8,
                'mime_type' => 'image/png',
                'size' => 2670,
                'url' => 'general/paypal.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:22',
                'updated_at' => '2022-01-04 04:21:22',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'user_id' => 0,
                'name' => 'visa',
                'folder_id' => 8,
                'mime_type' => 'image/png',
                'size' => 2841,
                'url' => 'general/visa.png',
                'options' => '[]',
                'created_at' => '2022-01-04 04:21:22',
                'updated_at' => '2022-01-04 04:21:22',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}