<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuNodesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_nodes')->delete();
        
        \DB::table('menu_nodes')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Home',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/products',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Products',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '#',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Shop',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 1,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'parent_id' => 3,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/television',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Product Category',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'parent_id' => 3,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Ecommerce\\Models\\Brand',
                'url' => '/brands/fashion-live',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Brand',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'parent_id' => 3,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductTag',
                'url' => '/product-tags/electronic',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Product Tag',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'parent_id' => 3,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => 'products/beat-headphone',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Product Single',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => 3,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/blog',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Blog',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 1,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'parent_id' => 8,
                'reference_id' => 3,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/blog',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Blog Left Sidebar',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'parent_id' => 8,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Blog\\Models\\Category',
                'url' => '/news/ecommerce',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Blog Category',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'parent_id' => 8,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Blog\\Models\\Tag',
                'url' => '/tags/general',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Blog Tag',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'parent_id' => 8,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => 'news/4-expert-tips-on-how-to-choose-the-right-mens-wallet',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Blog Single',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => 5,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/faq',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'FAQ',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => 2,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/contact-us',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Contact',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'parent_id' => 0,
                'reference_id' => 4,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/about-us',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'About Us',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'parent_id' => 0,
                'reference_id' => 5,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/faq',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'FAQ',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 2,
                'parent_id' => 0,
                'reference_id' => 6,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/location',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Location',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 2,
                'parent_id' => 0,
                'reference_id' => 7,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/affiliates',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Affiliates',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 2,
                'parent_id' => 0,
                'reference_id' => 2,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/contact-us',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Contact',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/television',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Television',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 2,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/home-audio-theaters',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Mobile',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 3,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/tv-videos',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Headphone',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 4,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/camera-photos-videos',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Watches',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 5,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/cellphones-accessories',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Game',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => 4,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/customer/overview',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'My profile',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            25 => 
            array (
                'id' => 26,
                'menu_id' => 4,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/wishlist',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Wishlist',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            26 => 
            array (
                'id' => 27,
                'menu_id' => 4,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => 'customer/orders',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Orders',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            27 => 
            array (
                'id' => 28,
                'menu_id' => 4,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/orders/tracking',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Order tracking',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            28 => 
            array (
                'id' => 29,
                'menu_id' => 5,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Trang chủ',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            29 => 
            array (
                'id' => 30,
                'menu_id' => 5,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/products',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Sản phẩm',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            30 => 
            array (
                'id' => 31,
                'menu_id' => 5,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '#',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Cửa hàng',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 1,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            31 => 
            array (
                'id' => 32,
                'menu_id' => 5,
                'parent_id' => 31,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/television',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Danh mục sản phẩm',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            32 => 
            array (
                'id' => 33,
                'menu_id' => 5,
                'parent_id' => 31,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Ecommerce\\Models\\Brand',
                'url' => '/brands/fashion-live',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Thương hiệu',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            33 => 
            array (
                'id' => 34,
                'menu_id' => 5,
                'parent_id' => 31,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductTag',
                'url' => '/product-tags/electronic',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Tag sản phẩm',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            34 => 
            array (
                'id' => 35,
                'menu_id' => 5,
                'parent_id' => 31,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => 'products/beat-headphone',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Sản phẩm chi tiết',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            35 => 
            array (
                'id' => 36,
                'menu_id' => 5,
                'parent_id' => 0,
                'reference_id' => 3,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/blog',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Tin tức',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 1,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            36 => 
            array (
                'id' => 37,
                'menu_id' => 5,
                'parent_id' => 36,
                'reference_id' => 3,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/blog',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Blog Left Sidebar',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            37 => 
            array (
                'id' => 38,
                'menu_id' => 5,
                'parent_id' => 36,
                'reference_id' => 5,
                'reference_type' => 'Botble\\Blog\\Models\\Category',
                'url' => NULL,
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Danh mục',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            38 => 
            array (
                'id' => 39,
                'menu_id' => 5,
                'parent_id' => 36,
                'reference_id' => 6,
                'reference_type' => 'Botble\\Blog\\Models\\Tag',
                'url' => NULL,
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Tag bài viết',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            39 => 
            array (
                'id' => 40,
                'menu_id' => 5,
                'parent_id' => 36,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => 'news/vi/4-expert-tips-on-how-to-choose-the-right-mens-wallet',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Bài viết chi tiết',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            40 => 
            array (
                'id' => 41,
                'menu_id' => 5,
                'parent_id' => 0,
                'reference_id' => 5,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/faq',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'FAQ',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            41 => 
            array (
                'id' => 42,
                'menu_id' => 5,
                'parent_id' => 0,
                'reference_id' => 2,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/contact-us',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Liên hệ',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            42 => 
            array (
                'id' => 43,
                'menu_id' => 6,
                'parent_id' => 0,
                'reference_id' => 4,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/about-us',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Về chúng tôi',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            43 => 
            array (
                'id' => 44,
                'menu_id' => 6,
                'parent_id' => 0,
                'reference_id' => 5,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/faq',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Hỏi đáp',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            44 => 
            array (
                'id' => 45,
                'menu_id' => 6,
                'parent_id' => 0,
                'reference_id' => 6,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/location',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Vị trí',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            45 => 
            array (
                'id' => 46,
                'menu_id' => 6,
                'parent_id' => 0,
                'reference_id' => 7,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/affiliates',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Chi nhánh',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            46 => 
            array (
                'id' => 47,
                'menu_id' => 6,
                'parent_id' => 0,
                'reference_id' => 2,
                'reference_type' => 'Botble\\Page\\Models\\Page',
                'url' => '/contact-us',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Liên hệ',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            47 => 
            array (
                'id' => 48,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 1,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/television',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Tivi',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            48 => 
            array (
                'id' => 49,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 2,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/home-audio-theaters',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Di động',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            49 => 
            array (
                'id' => 50,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 3,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/tv-videos',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Tai nghe',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            50 => 
            array (
                'id' => 51,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 4,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/camera-photos-videos',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Đồng hồ',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            51 => 
            array (
                'id' => 52,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 5,
                'reference_type' => 'Botble\\Ecommerce\\Models\\ProductCategory',
                'url' => '/product-categories/cellphones-accessories',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Trò chơi',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            52 => 
            array (
                'id' => 53,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/customer/overview',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Tài khoản của tôi',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            53 => 
            array (
                'id' => 54,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/wishlist',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Danh sách yêu thích',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            54 => 
            array (
                'id' => 55,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => 'customer/orders',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Đơn hàng',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
            55 => 
            array (
                'id' => 56,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => NULL,
                'reference_type' => NULL,
                'url' => '/orders/tracking',
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Theo dõi đơn hàng',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2022-01-04 04:21:20',
                'updated_at' => '2022-01-04 04:21:20',
            ),
        ));
        
        
    }
}