<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PaymentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('payments')->delete();
        
        \DB::table('payments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => '2APTDTUHSV',
                'payment_channel' => 'mollie',
                'description' => NULL,
                'amount' => '1606.00',
                'order_id' => 1,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 5,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'C2AIWIVJGY',
                'payment_channel' => 'cod',
                'description' => NULL,
                'amount' => '735.70',
                'order_id' => 2,
                'status' => 'pending',
                'payment_type' => 'confirm',
                'customer_id' => 7,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'LZDDXHIKH4',
                'payment_channel' => 'paystack',
                'description' => NULL,
                'amount' => '483.90',
                'order_id' => 3,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 2,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => '8HXZZ1WVR4',
                'payment_channel' => 'cod',
                'description' => NULL,
                'amount' => '624.80',
                'order_id' => 4,
                'status' => 'pending',
                'payment_type' => 'confirm',
                'customer_id' => 10,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => '2EDICT1CJI',
                'payment_channel' => 'paypal',
                'description' => NULL,
                'amount' => '1542.80',
                'order_id' => 5,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 1,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'I2JGOWBSRX',
                'payment_channel' => 'bank_transfer',
                'description' => NULL,
                'amount' => '956.90',
                'order_id' => 6,
                'status' => 'pending',
                'payment_type' => 'confirm',
                'customer_id' => 11,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'L0JTAPUBT1',
                'payment_channel' => 'bank_transfer',
                'description' => NULL,
                'amount' => '660.00',
                'order_id' => 7,
                'status' => 'pending',
                'payment_type' => 'confirm',
                'customer_id' => 3,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => '4ZRFXVMTVC',
                'payment_channel' => 'paystack',
                'description' => NULL,
                'amount' => '430.50',
                'order_id' => 8,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 2,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'RWKZ2QZ2TF',
                'payment_channel' => 'razorpay',
                'description' => NULL,
                'amount' => '1330.00',
                'order_id' => 9,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 2,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => '5LHFDAQ0VU',
                'payment_channel' => 'cod',
                'description' => NULL,
                'amount' => '276.10',
                'order_id' => 10,
                'status' => 'pending',
                'payment_type' => 'confirm',
                'customer_id' => 4,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'BHAV2ACTNP',
                'payment_channel' => 'paypal',
                'description' => NULL,
                'amount' => '240.35',
                'order_id' => 11,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 3,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'P0DYAKSRCQ',
                'payment_channel' => 'cod',
                'description' => NULL,
                'amount' => '1965.50',
                'order_id' => 12,
                'status' => 'pending',
                'payment_type' => 'confirm',
                'customer_id' => 5,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'HOTVQZBXQV',
                'payment_channel' => 'stripe',
                'description' => NULL,
                'amount' => '1533.90',
                'order_id' => 13,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 11,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'JDSVLIQCVA',
                'payment_channel' => 'cod',
                'description' => NULL,
                'amount' => '304.50',
                'order_id' => 14,
                'status' => 'pending',
                'payment_type' => 'confirm',
                'customer_id' => 9,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'D0YK2XUATR',
                'payment_channel' => 'razorpay',
                'description' => NULL,
                'amount' => '608.55',
                'order_id' => 15,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 6,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'ITV5GFHYC2',
                'payment_channel' => 'bank_transfer',
                'description' => NULL,
                'amount' => '284.50',
                'order_id' => 16,
                'status' => 'pending',
                'payment_type' => 'confirm',
                'customer_id' => 10,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'ICLAB2LIUN',
                'payment_channel' => 'bank_transfer',
                'description' => NULL,
                'amount' => '1069.80',
                'order_id' => 17,
                'status' => 'pending',
                'payment_type' => 'confirm',
                'customer_id' => 6,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:38',
                'updated_at' => '2022-03-20 14:06:38',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => '27GJFAOFXJ',
                'payment_channel' => 'mollie',
                'description' => NULL,
                'amount' => '426.70',
                'order_id' => 18,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 6,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:39',
                'updated_at' => '2022-03-20 14:06:39',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'Y7ZUNXAWY0',
                'payment_channel' => 'mollie',
                'description' => NULL,
                'amount' => '518.83',
                'order_id' => 19,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 3,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:39',
                'updated_at' => '2022-03-20 14:06:39',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'currency' => 'USD',
                'user_id' => 0,
                'charge_id' => 'QYI2DYBBDZ',
                'payment_channel' => 'stripe',
                'description' => NULL,
                'amount' => '745.90',
                'order_id' => 20,
                'status' => 'completed',
                'payment_type' => 'confirm',
                'customer_id' => 11,
                'refunded_amount' => NULL,
                'refund_note' => NULL,
                'created_at' => '2022-03-20 14:06:39',
                'updated_at' => '2022-03-20 14:06:39',
                'customer_type' => 'Botble\\Ecommerce\\Models\\Customer',
                'metadata' => NULL,
            ),
        ));
        
        
    }
}